#!/bin/bash
# Group MEG Bot - Command Reference
# Developer: Latiful Hassan Zihan 🇧🇩
# Version: 2.1.0

echo "🤖 Group MEG Bot - Command Reference 🛡️"
echo "=========================================="

echo ""
echo "🔧 SETUP COMMANDS:"
echo "==================="
echo "# Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Setup data files"
echo "python setup_data.py"
echo ""
echo "# Start the bot"
echo "python group_meg_bot.py"
echo ""

echo "🎯 BOT COMMANDS:"
echo "================="

echo ""
echo "🔥 General Commands:"
echo "/start          - 🚀 Start bot & get 'Add to Group' buttons"
echo "/help           - 📚 Show all commands"
echo "/about          - ℹ️ Bot information"
echo "/developer      - 👨‍💻 Developer contact"
echo "/settings       - ⚙️ Open control panel (Admins only)"
echo "/rules          - 📜 View group rules"

echo ""
echo "👮‍♂️ Admin Commands:"
echo "/kick           - 👢 Kick user (reply to message)"
echo "/ban            - 🚫 Ban user (reply to message)"
echo "/unban <id>     - ✅ Unban user by ID"
echo "/mute <seconds> - 🔇 Mute user temporarily"
echo "/unmute         - 🔊 Unmute user (reply to message)"
echo "/warn           - ⚠️ Warn user (reply to message)"
echo "/purge          - 🧹 Delete 50 recent messages"
echo "/admins         - 👑 List all group admins"

echo ""
echo "👥 Role Management:"
echo "/roles          - 👑 Role management panel"
echo "/addrole <role> - ➕ Assign role (reply to user)"
echo "/removerole <role> - ➖ Remove role (reply to user)"
echo "/userroles      - 👤 Check user roles (reply to user)"
echo ""
echo "Available roles: moderator, helper, vip"

echo ""
echo "🔧 Configuration Commands:"
echo "/setrules <text>    - 📜 Set custom group rules"
echo "/setwelcome <text>  - 👋 Set welcome message"
echo "/blacklist <word>   - 🚫 Add word to blacklist"
echo "/info              - ℹ️ Get user info (reply to message)"

echo ""
echo "💡 QUICK EXAMPLES:"
echo "==================="
echo "# Basic setup"
echo "/start                    # Get setup buttons"
echo "/settings                 # Open control panel"
echo ""
echo "# Admin actions"
echo "/kick                     # Reply to user's message"
echo "/ban                      # Reply to user's message"
echo "/warn spam posting        # Reply with reason"
echo ""
echo "# Role management"
echo "/addrole moderator        # Reply to user"
echo "/removerole helper        # Reply to user"
echo "/userroles               # Reply to check roles"
echo ""
echo "# Configuration"
echo "/setrules Be respectful and have fun!"
echo "/setwelcome Welcome {mention} to {group}!"

echo ""
echo "🚀 DEPLOYMENT COMMANDS:"
echo "========================"
echo "# Create virtual environment"
echo "python -m venv venv"
echo ""
echo "# Activate virtual environment (Linux/Mac)"
echo "source venv/bin/activate"
echo ""
echo "# Activate virtual environment (Windows)"
echo "venv\\Scripts\\activate"
echo ""
echo "# Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Run bot in background (Linux)"
echo "nohup python group_meg_bot.py > logs/bot.log 2>&1 &"
echo ""
echo "# Check bot process"
echo "ps aux | grep group_meg_bot.py"
echo ""
echo "# Stop bot process"
echo "pkill -f group_meg_bot.py"

echo ""
echo "🔍 TROUBLESHOOTING:"
echo "===================="
echo "# Check if bot token is set"
echo "grep 'YOUR_BOT_TOKEN_HERE' data/config.json"
echo ""
echo "# View bot logs"
echo "tail -f logs/bot.log"
echo ""
echo "# Check data files"
echo "ls -la data/"
echo ""
echo "# Test bot locally"
echo "python -c \"import telegram; print('✅ python-telegram-bot installed')\""

echo ""
echo "📊 MAINTENANCE COMMANDS:"
echo "========================="
echo "# Backup data"
echo "tar -czf backups/backup_\$(date +%Y%m%d_%H%M%S).tar.gz data/"
echo ""
echo "# Restore from backup"
echo "tar -xzf backups/backup_YYYYMMDD_HHMMSS.tar.gz"
echo ""
echo "# Clear logs older than 7 days"
echo "find logs/ -name '*.log' -mtime +7 -delete"
echo ""
echo "# Check disk usage"
echo "du -sh data/ backups/ logs/"

echo ""
echo "🎯 MOST USED COMMANDS:"
echo "======================="
echo "1. /start          - First command to run"
echo "2. /settings       - Main control panel"  
echo "3. /addrole vip    - Assign VIP role"
echo "4. /kick          - Remove troublemakers"
echo "5. /warn          - Issue warnings"

echo ""
echo "👨‍💻 Developer: Latiful Hassan Zihan 🇧🇩"
echo "📱 Telegram: @alwayszihan"
echo "🇵🇸 Free Palestine! 🇧🇩 Bangladesh Zindabad!"
echo "=========================================="
