services:
  - type: web
    name: group-meg-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python group_meg_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
